### PR TITLE
Restore Close/Read/Write methods for streams

### PR DESCRIPTION
**Pull request by vincentbernat**
They make streams implement Reader/Writer/Closer interfaces which makes them usable by a lot of functions.

### CODE REVIEW

**Comment by berrange** [comment]
The reasons these methods were renamed is that they create the possibility of conflicts with future method names that may be exported by the libvirt C library. We want to strive to have all the method names in Go binding, match corresponding libvirt C library API names, for anything in the "libvirt" package namespace. 

Any extra Go specific methods we want to introduce need to be part of  a separate package namespace. eg a libvirtutils package.

**Comment by vincentbernat** [comment]
How strict should this rule be? For example, don't the Python bindings implement some of the `__` magic methods (I didn't check)? Of course, that's a bit different since it's unlikely that the C API will come with functions starting with `__`.

Also, the same kind of problems exist with Java when using try-with-resources. Do the Java bindings do something special for that pattern?

In Java, you can still inherit, but you cannot with Go. A user can still "alias" a Stream into its own Stream:

```go
type Stream libvirt.Stream
func (v *Stream) Read(p []byte) (int, error) {
   return v.Recv(p)
}
```

But for Go, this is a totally different type. The user will have to cast from the original type to its own type. Not convenient. It could also compose its own type but there are similar limitations.

**Comment by vincentbernat** [comment]
Note that I don't personally use the streams. So, I am also fine with doing nothing. Initially, I thought you did overlook why the names in the Go binding didn't match the ones from libvirt.

**Comment by berrange** [comment]
I was thinking of creating an "adapter" class that implements the Go I/O routines, similar to what you show, but without type-casting.

type StreamIO struct {
   Stream libvirt.Stream
}

func NewStreamIO(s libvirt.Stream) *StreamIO {
    return &StreamIO{Stream: s}
}

func (sio *StreamIO) Read(p []byte) (int, error) {
   return sio.Stream.Recv(p)
}


which should be easy enough for apps to use

**Comment by rmohr** [comment]
Just recently needed that in the code and did a wrapper like mentioned here. It is really very common that you need support for these interfaces in Go, but I also understand the concern regarding overlapping functionality. 

I would slightly favour having the Read() and Write() (maybe also a close which hides the free()) on the object.

**Comment by purpleidea** [comment]
On Fri, Dec 30, 2016 at 12:13 PM, Daniel Berrange <notifications@github.com>
wrote:

> I was thinking of creating an "adapter" class that implements the Go I/O
> routines, similar to what you show, but without type-casting.


What about these?

https://golang.org/pkg/io/#Writer
https://golang.org/pkg/io/#Reader

??

HTH

**Comment by rmohr** [comment]
And here is the Closer interface

https://golang.org/pkg/io/#Closer

**Comment by berrange** [comment]
Closing because this proposed patch is not suitable for merge.

**Pull request closed without merging**
